// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAbil8_Sistema_Verificação_dupla.slnx.Model.Context;

#nullable disable

namespace WebAbil8_Sistema_Verificação_dupla.slnx.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510160613_UpdateEntidades")]
    partial class UpdateEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dataCriacao");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomeCompleto");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senhaHash");

                    b.HasKey("Id");

                    b.ToTable("administrador");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Ambiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dataCriacao");

                    b.Property<int>("DispositivoT50Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dispositivoT50Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("TempoEsperaGravacaoSeg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tempoEsperaGravacaoSeg");

                    b.HasKey("Id");

                    b.ToTable("ambiente");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.AmbientePessoa", b =>
                {
                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ambienteId");

                    b.Property<long>("PessoaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pessoaId");

                    b.Property<DateTime>("DataAdicionado")
                        .HasColumnType("TEXT")
                        .HasColumnName("dataAdicionado");

                    b.HasKey("AmbienteId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("ambiente_pessoa");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ambienteId");

                    b.Property<string>("EnderecoONVIF")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("enderecoONVIF");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo");

                    b.Property<string>("UrlRTSP")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("urlRTSP");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("camera");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("RetencaoGravacoesTentativasDias")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retencaoGravacoesTentativasDias");

                    b.Property<int>("RetencaoLogsDias")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retencaoLogsDias");

                    b.Property<int>("TempoEsperaGravacaoSeg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tempoEsperaGravacaoSeg");

                    b.HasKey("Id");

                    b.ToTable("configuracao");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.DispositivoT50", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DigitaisCadastradas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("digitaisCadastradas");

                    b.Property<string>("EnderecoIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("enderecoIP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Porta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("porta");

                    b.HasKey("Id");

                    b.ToTable("dispositivoT50");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.LogAdmin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("acao");

                    b.Property<int>("AdminId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adminId");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dataExpiracao");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT")
                        .HasColumnName("dataHora");

                    b.Property<string>("EntidadeAfetada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entidadeAfetada");

                    b.Property<int?>("EntidadeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entidadeId");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("logAdmin");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("biometriaCadastrada")
                        .HasColumnType("DATETIME")
                        .HasColumnName("biometriaCadastrada");

                    b.Property<DateTime?>("dataCadastro")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("dataCadastro");

                    b.Property<DateTime?>("dataUltimoAcesso")
                        .HasColumnType("DATETIME")
                        .HasColumnName("dataUltimoAcesso");

                    b.Property<string>("modoAcesso")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("modoAcesso");

                    b.Property<string>("senhaClear")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senhaClear");

                    b.Property<string>("senhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senhaHash");

                    b.Property<byte[]>("templateBackup")
                        .HasColumnType("BLOB")
                        .HasColumnName("templateBackup");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.SenhaDisponivel", b =>
                {
                    b.Property<string>("Senha")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("senha");

                    b.Property<bool>("EmUso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("emUso");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pessoaId");

                    b.HasKey("Senha");

                    b.HasIndex("PessoaId");

                    b.ToTable("senhaDisponivel");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.TentativaAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("AcessoLiberado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acessoLiberado");

                    b.Property<int>("AmbienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ambienteId");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dataExpiracao");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT")
                        .HasColumnName("dataHora");

                    b.Property<string>("GravacaoPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gravacaoPath");

                    b.Property<string>("MotivoNegacao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("motivoNegacao");

                    b.Property<long?>("Pessoa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pessoaId");

                    b.Property<string>("TipoVerificacao")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("tipoVerificacao");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("tentativaAcesso");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.AmbientePessoa", b =>
                {
                    b.HasOne("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiente");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Camera", b =>
                {
                    b.HasOne("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiente");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.LogAdmin", b =>
                {
                    b.HasOne("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.SenhaDisponivel", b =>
                {
                    b.HasOne("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WebAbil8_Sistema_Verificação_dupla.slnx.Model.TentativaAcesso", b =>
                {
                    b.HasOne("WebAbil8_Sistema_Verificação_dupla.slnx.Model.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiente");
                });
#pragma warning restore 612, 618
        }
    }
}
